export const AUTH_LOADING = "AUTH_LOADING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT = "LOGOUT"
export const AUTH_ERROR = "AUTH_ERROR"

export const PRODUCT_LOADING = "PRODUCT_LOADING" 
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS" 
export const PRODUCT_ERROR = "PRODUCT_ERROR" 
export const RESET_PRODUCT_STATE = "RESET_PRODUCT_STATE" 

export const CUSTOMER_LOADING = "CUSTOMER_LOADING"
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS"
export const CUSTOMER_ERROR = "CUSTOMER_ERROR"
export const RESET_CUSTOMER_STATE = "RESET_CUSTOMER_STATE"

export const ORDER_LOADING = "ORDER_LOADING"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_ERROR = "ORDER_ERROR"
export const RESET_ORDER_STATE = "RESET_ORDER_STATE"

export const PRODUCT_LIST_LOADING = "PRODUCT_LIST_LOADING" 
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS" 
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR" 
export const RESET_PRODUCT_LIST_STATE = "RESET_PRODUCT_LIST_STATE" 

export const CUSTOMER_LIST_LOADING = "CUSTOMER_LIST_LOADING"
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS"
export const CUSTOMER_LIST_ERROR = "CUSTOMER_LIST_ERROR"
export const RESET_CUSTOMER_LIST_STATE = "RESET_CUSTOMER_LIST_STATE"

export const ORDER_LIST_LOADING = "ORDER_LIST_LOADING"
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_ERROR = "ORDER_LIST_ERROR"
export const RESET_ORDER_LIST_STATE = "RESET_ORDER_LIST_STATE"

export const PRODUCT_BY_SALES_LOADING = "PRODUCT_BY_SALES_LOADING" 
export const PRODUCT_BY_SALES_SUCCESS = "PRODUCT_BY_SALES_SUCCESS" 
export const PRODUCT_BY_SALES_ERROR = "PRODUCT_BY_SALES_ERROR" 
export const RESET_PRODUCT_BY_SALES_STATE = "RESET_PRODUCT_BY_SALES_STATE" 

export const STATISTICAL_INFO_LOADING = "STATISTICAL_INFO_LOADING"
export const STATISTICAL_INFO_SUCCESS = "STATISTICAL_INFO_SUCCESS"
export const STATISTICAL_INFO_ERROR = "STATISTICAL_INFO_ERROR"
export const RESET_STATISTICAL_INFO_STATE = "RESET_STATISTICAL_INFO_STATE"